spring:
  application:
    name: finance-service

server:
  port: 8301

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

